[tool.poetry]
name = "csdmpy"
version = "0.1.0"
description = "Python port of Social Finance's children's social care demand model"
authors = ["dezog"]

[tool.poetry.dependencies]
python = "^3.8.5"
pandas = "1.0.5"
numpy = "1.17.5"

[tool.poetry.dev-dependencies]
pytest = "^7.1"
coverage = "^6.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
